#!/usr/bin/env bash

set -e

num_cores=0
if [[ -f /proc/cpuinfo ]]
then
    num_cores=$(cat /proc/cpuinfo | grep -c processor)
fi

pushd "$(dirname $(readlink -f "${BASH_SOURCE[0]}"))" >/dev/null

export PREFIX=$(pwd)

export CC=clang
export CXX=clang++

rm -rf work
mkdir work
cd work

wget http://ftp.gnu.org/gnu/binutils/binutils-2.26.1.tar.bz2
tar jxf binutils-2.26.1.tar.bz2
mv binutils-2.26.1 binutils

mkdir build
cd build

export TARGET=x86_64-elf
../binutils/configure --target=$TARGET --prefix=$PREFIX --disable-nls --disable-werror
make all -j${num_cores} -l${num_cores}
make install -j${num_cores} -l${num_cores}

rm -rf *

export TARGET=x86_64-w64-mingw32
../binutils/configure --target=$TARGET --prefix=$PREFIX --disable-nls --disable-werror
make all -j${num_cores} -l${num_cores}
make install -j${num_cores} -l${num_cores}

cd ../..
rm -rf work

popd >/dev/null

