#!/bin/sh

set -ex

cd "$(dirname $(readlink -f "$0"))"

ncpus="$(grep -c processor /proc/cpuinfo 2>/dev/null || echo 1)"

export PREFIX="$(pwd)"

export CC=clang
export CXX=clang++

rm -rf work
mkdir work
cd work

wget http://ftp.gnu.org/gnu/binutils/binutils-2.26.1.tar.bz2 || curl -SOL http://ftp.gnu.org/gnu/binutils/binutils-2.26.1.tar.bz2
tar jxf binutils-2.26.1.tar.bz2
mv binutils-2.26.1 binutils

for tgt in x86_64-elf x86_64-w64-mingw32; do
    mkdir "build-$tgt"
    cd "build-$tgt"

    export TARGET="$tgt"
    ../binutils/configure --target="$TARGET" --prefix="$PREFIX" --disable-nls --disable-werror
    make all -j${ncpus} -l${num_cores}
    make install -j${ncpus} -l${num_cores}

	cd ..
done

cd ..
rm -rf work
